;;; color-theme-dawn-night.el --- color theme of dawn and night.
;; color-theme-dawn-night.el contains two customized color themes:
;; (1) cl-night
;; is a dark-background theme, designed for normal programming,
;; org/muse mode editing and LaTeX editing. The foreground colors are designed
;; to be somewhat aqua, with a bright and warm feeling. 
;; (2) cl-dawn
;; is designed with a bright and warm background. The color setup was inspired
;; by the light yellow background and visual effect of the Matlab programming
;; environment.

;; Copyright 2007-2012 Da Zhang

;; Author: Da Zhang
;; Version: 1.0

;; How to use: 

;; Call function
;; switch-dawn-night to change to the dark face, and call C-u
;; switch-dawn-night for the bright background face.

;; Install the theme:
;; (1)Place color-theme-dawn-night.el into your load-path.

;; (2)In your .emacs, add:
;; (require 'color-theme-dawn-night)

;; (3)optional keybinding
;; (global-set-key [f6] 'switch-dawn-night)

;; notes about exotic face names:
;; 1. hl-line: the hightlighed current line
;; 2. mode-line-XXX: the info bar near the bottom of the frame
;; 3. hilight: in dired, the face of where your mouse is pointing at
;; 4. diredp-XXX: the color theme for dired-plus, dired-details+ ...


;; Copyright (C) 2012 Da Zhang, zhangda@ieee.org

;; This is free software; you can redistribute it and/or modify it under the
;; terms of the GNU General Public License as published by the Free Software
;; Foundation; either version 2, or (at your option) any later version.
;;
;; This is distributed in the hope that it will be useful, but WITHOUT ANY
;; WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
;; A PARTICULAR PURPOSE. See the GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License along with
;; GNU Emacs; see the file COPYING. If not, write to the Free Software
;; Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

;;;;;;;;;;;;;;;;;;;;;;;;;;; -*- Mode: Emacs-Lisp -*- ;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Code:

(defun cl-night ()
  "Dark color theme (night), ."
  (interactive)
  (ignore-errors  (color-theme-install
                   '(color-theme-da-normal
                     (background-color . "black")
                     (background-mode . dark)
                     (background-toolbar-color . "#cf3ccf3ccf3c")
                     (border-color . "#000000000000")
                     (bottom-toolbar-shadow-color . "#79e77df779e7")
                     (foreground-color . "honeydew")
                     (default ((t (:stipple nil :background "#272727" :foreground "honeydew3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :foundry "outline" :family "Bitstream Vera Sans Mono"))))
                     (bbdb-company ((t (nil))))
                     (bbdb-field-name ((t (:bold t :weight bold))))
                     (bbdb-field-value ((t (nil))))
                     (bbdb-name ((t (:underline t))))
                     (blue ((t (:foreground "blue"))))
                     (bm-persistent-face ((t (:foreground "white" :background "darkblue" :weight bold ))))
                     (bm-fringe-persistent-face ((t (:foreground "white" :background "darkblue" :weight bold))))
                     (bold ((t (:bold t :weight bold))))
                     (bold-italic ((t (:bold t :italic t :slant italic :weight bold))))
                     (border ((t (:background "#000000000000"))))
                     (border-glyph ((t (nil))))
                     (buffer-menu-buffer ((t (:bold t :weight bold))))
                     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
                     (button ((t (:underline t))))
                     (comint-highlight-prompt ((t (:bold t :weight bold))))
                     (compilation-column-number ((t (:foreground "DarkSlateGray1"))))
                     (compilation-error ((t (:bold t :weight bold :foreground "Red"))))
                     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
                     (compilation-line-number ((t (:foreground "magenta2"))))
                     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
                     (completions-common-part ((t (:width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "gray78" :background "black" :stipple nil))))
                     (completions-first-difference ((t (:bold t :weight bold))))
                     (cperl-array-face ((t (:bold t :foreground "SkyBlue2" :weight bold))))
                     (cperl-hash-face ((t (:foreground "LightBlue2"))))
                     (cperl-invalid-face ((t (:foreground "red"))))
                     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
                     (cursor ((t (:background "red"))))
                     (custom-button ((t (:bold t :weight bold :box (:line-width 2 :style released-button)))))
                     (custom-button-face ((t (:bold t :weight bold))))
                     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
                     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
                     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
                     (custom-button-unraised ((t (:underline t))))
                     (custom-changed ((t (:background "blue" :foreground "white"))))
                     (custom-changed-face ((t (:background "blue" :foreground "white"))))
                     (custom-comment ((t (:foreground "white"))))
                     (custom-comment-face ((t (:foreground "white"))))
                     (custom-comment-tag ((t (:foreground "white"))))
                     (custom-comment-tag-face ((t (:foreground "white"))))
                     (custom-documentation ((t (nil))))
                     (custom-documentation-face ((t (nil))))
                     (custom-face-tag ((t (:underline t))))
                     (custom-face-tag-face ((t (:underline t))))
                     (custom-group-tag ((t (:foreground "dark goldenrod yellow" :weight bold :underline t))))
                     (custom-group-tag-1 ((t (:foreground "red" :underline t))))
                     (custom-group-tag-face ((t (:foreground "dark goldenrod yellow" :weight bold :underline t))))
                     (custom-group-tag-face-1 ((t (:foreground "red" :underline t))))
                     (custom-invalid ((t (:background "red" :foreground "yellow"))))
                     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
                     (custom-link ((t (:underline t :foreground "cyan1"))))
                     (custom-modified ((t (:background "blue" :foreground "white"))))
                     (custom-modified-face ((t (:background "blue" :foreground "white"))))
                     (custom-rogue ((t (:background "black" :foreground "pink"))))
                     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
                     (custom-saved ((t (:underline t))))
                     (custom-saved-face ((t (:underline t))))
                     (custom-set ((t (:background "white" :foreground "blue"))))
                     (custom-set-face ((t (:background "white" :foreground "blue"))))
                     (custom-state ((t (:foreground "white"))))
                     (custom-state-face ((t (:foreground "white"))))
                     (custom-themed ((t (:background "blue1" :foreground "white"))))
                     (custom-variable-button ((t (:bold t :underline t :weight bold))))
                     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
                     (custom-variable-tag ((t (:foreground "burlywood" :underline t))))
                     (custom-variable-tag-face ((t (:foreground "burlywood" :underline t))))
                     (cvs-filename-face ((t (:foreground "Green1"))))
                     (cvs-handled-face ((t (:foreground "pink"))))
                     (cvs-header-face ((t (:foreground "green"))))
                     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
                     (cvs-msg-face ((t (:foreground "red"))))
                     (cvs-need-action-face ((t (:foreground "yellow"))))
                     (cvs-unknown-face ((t (:foreground "grey"))))
                     (diff-added-face ((t (nil))))
                     (diff-changed-face ((t (nil))))
                     (diff-file-header-face ((t (:bold t :background "grey70" :weight bold))))
                     (diff-hunk-header-face ((t (:background "grey85"))))
                     (diff-index-face ((t (:bold t :background "grey70" :weight bold))))
                     (diff-removed-face ((t (nil))))
                     ;; default faces from dired.el
                     (dired-header ((t (:inherit default :foreground "YellowGreen2"))))
                     (dired-marked ((t (:foreground "DarkOrange2" :weight bold))))
                     (dired-flagged ((t (:background "LightSlateGray"))))
                     (dired-perm-write ((t (:inherit default :foreground "Red2"))))
                     (dired-directory ((t (:bold t :foreground "SkyBlue" :weight bold))))
                     (dired-symlink ((t (:foreground "cyan"))))
                     (dired-ignored ((t (:inherit shadow :foreground "gray40"))))
                     (dired-boring ((t (:foreground "Gray65"))))
                     (dired-executable ((t (:foreground "Green"))))
                     (dired-setuid ((t (:foreground "Red"))))
                     (dired-socket ((t (:foreground "magenta"))))
                     ;; faces from dired+
                     (diredp-dir-heading ((t (:foreground "Brick" :weight bold ))))
                     (diredp-dir-priv ((t (:foreground "burlywood3" :weight bold))))
                     (diredp-no-priv ((t )))
                     (diredp-number ((t (:foreground "burlywood3"))))
                     (diredp-file-name ((t (:foreground "gray80" :weight bold))))
                     (diredp-compressed-file-suffix ((t (:foreground "gray70" :weight normal))))
                     (diredp-file-suffix ((t (:foreground "gray70" :weight normal))))
                     (diredp-exec-priv ((t (:foreground "LightSkyBlue" :weight bold))))
                     (diredp-read-priv ((t (:foreground "green3" :weight bold))))
                     (diredp-write-priv ((t (:foreground "Red2" :weight bold))))
                     (diredp-link-priv ((t (:foreground "gray60" :underline t))))
                     (diredp-other-priv ((t (:foreground "gray30"))))
                     (diredp-rare-priv ((t (:foreground "red"))))
                     (diredp-flag-mark-line ((t (:background "DarkOrange2"))))
					 (diredp-date-time ((t (:foreground "honeydew3"))))
                     (diredp-ignored-file-name ((t (:foreground "gray50"))))
                     (ecb-analyse-bucket-element-face ((t (:height 1.0))))
                     (ecb-analyse-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
                     (ecb-analyse-face ((t (:background "magenta"))))
                     (ecb-analyse-general-face ((t (:height 1.0))))
                     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
                     (ecb-default-general-face ((t (:height 1.0))))
                     (ecb-default-highlight-face ((t (:background "magenta"))))
                     (ecb-directories-general-face ((t (:height 1.0))))
                     (ecb-directory-face ((t (:background "magenta"))))
                     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
                     (ecb-history-face ((t (:background "magenta"))))
                     (ecb-history-general-face ((t (:height 1.0))))
                     (ecb-method-face ((t (:background "magenta"))))
                     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
                     (ecb-methods-general-face ((t (:height 1.0))))
                     (ecb-mode-line-data-face ((t (nil))))
                     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
                     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
                     (ecb-source-face ((t (:background "magenta"))))
                     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1" :height 1.0))))
                     (ecb-source-read-only-face ((t (:italic t :slant italic))))
                     (ecb-sources-general-face ((t (:height 1.0))))
                     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
                     (ecb-tree-guide-line-face ((t (:foreground "gray" :height 1.0))))
                     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
                     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
                     (ediff-fine-diff-A ((t (:foreground "navy" :background "sky blue"))))
                     (ediff-fine-diff-B ((t (:foreground "navy" :background "sky blue"))))
                     (ediff-current-diff-A ((t (:foreground "gray80" :background "#0A246F"))))
                     (ediff-current-diff-B ((t (:foreground "gray80" :background "#0A246F"))))                     
                     (ediff-even-diff-A ((t (:foreground "gray80" :background "DarkSlateGray5"))))
                     (ediff-even-diff-B ((t (:foreground "gray80" :background "DarkSlateGray5"))))
                     (ediff-odd-diff-A ((t (:foreground "gray80" :background "DarkSlateGray5"))))
                     (ediff-odd-diff-B ((t (:foreground "gray80" :background "DarkSlateGray5"))))
                     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
                     (escape-glyph ((t (:foreground "cyan"))))
                     (excerpt ((t (nil))))
                     (file-name-shadow ((t (:foreground "grey50"))))
                     (fixed ((t (:bold t :weight bold))))
                     (fixed-pitch ((t (:family "courier"))))
                     (flyspell-duplicate ((t (:foreground "Red3" :underline t :weight bold))))
                     (flyspell-incorrect ((t (:foreground "Red1" :underline t :weight bold))))
                     (font-lock-builtin-face ((t (:foreground "red3" :weight bold))))
                     (font-lock-comment-delimiter-face ((t (:foreground "YellowGreen" :weight ultra-bold))))
                     (font-lock-comment-face ((t (:foreground "YellowGreen" :weight bold))))
                     (font-lock-constant-face ((t (:foreground "DarkOrange2" :weight normal))))
                     (font-lock-doc-face ((t (:foreground "burlywood"))))
                     (font-lock-doc-string-face ((t (:foreground "turquoise" :weight bold))))
                     (font-lock-function-name-face ((t (:foreground "white" :weight ultra-bold))))
                     (font-lock-keyword-face ((t (:bold t :foreground "DodgerBlue" :weight ultra-bold))))
                     (font-lock-negation-char-face ((t (nil))))
                     (font-lock-preprocessor-face ((t (:foreground "green3" :weight bold))))
                     (font-lock-reference-face ((t (:foreground "red3" :weight bold))))
                     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
                     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
                     (font-lock-string-face ((t (:foreground "burlywood" :weight bold))))
                     (font-lock-type-face ((t (:foreground "brown2" :weight bold))))
                     (font-lock-variable-name-face ((t (:foreground "magenta2" :weight bold))))
                     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight ultra-bold))))
                     (font-latex-math-face ((t (:foreground "burlywood"))))
                     (font-latex-sedate-face ((t (:foreground "gray60"))))
                     (font-latex-sectioning-5-face ((t (:weight bold :bold t :foreground "red3"))))
                     (font-latex-bold-face ((t (:weight bold :bold t :foreground "green3"))))
                     (font-latex-string-face ((t (:weight bold :bold nil :foreground "darkgreen"))))
                     (fringe ((t (:background "grey10" :foreground "#44AACC"))));;this is what change the boundaries on both sides of the emacs window
                     (green ((t (:foreground "green"))))
                     (gui-button-face ((t (:background "grey75" :foreground "black"))))
                     (gui-element ((t (nil))))
                     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
                     (help-argument-name ((t (nil))))
                     (highlight ((t (:background "#0A247A"))))
                     (hl-line ((t (:background "#1F2F3F"))));; use to be #112233
                     (html-helper-bold-face ((t (:bold t :weight bold))))
                     (html-helper-italic-face ((t (:bold t :foreground "yellow" :weight bold))))
                     (html-helper-underline-face ((t (:underline t))))
                     (hyper-apropos-documentation ((t (:foreground "LightSlateGray"))))
                     (hyper-apropos-heading ((t (:bold t :weight bold))))
                     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
                     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
                     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
                     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
                     (ibuffer-deletion-face ((t (:foreground "red"))))
                     (ibuffer-marked-face ((t (:foreground "green"))))
                     (ido-first-match ((t (:foreground "green3" :bold t :weight ultra-bold))))
                     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
                     (ido-only-match ((t (:foreground "Green" :weight ultra-bold))))
                     (ido-subdir ((t (:foreground "red"))))
                     (info-node ((t (:bold t :foreground "yellow" :weight bold))))
                     (info-xref ((t (:bold t :weight bold :underline t))))
                     (isearch ((t (:background "paleturquoise" :foreground "dark red"))))
                     (isearch-secondary ((t (:foreground "red3"))))
                     (isearch-fail ((t (:background "red" :foreground "black"))))
                     (italic ((t ( :italic t :slant italic))))
                     (lazy-highlight ((t (:background "paleturquoise4"))))
                     (left-margin ((t (nil))))
                     (link ((t (:foreground "dodger blue" :underline t))))
                     (link-visited ((t (:underline t :foreground "violet"))))
                     (linum ((t (:inherit shadow :foreground "burlywood" :height 90 :weight normal))))
                     (list-mode-item-selected ((t (:background "gray68" :foreground "dark green"))))
                     (man-bold ((t (:bold t :weight bold))))
                     (man-heading ((t (:bold t :weight bold))))
                     (man-italic ((t (:foreground "yellow" :italic t))))
                     (man-xref ((t (:underline t))))
                     (match ((t (:background "RoyalBlue3"))))
                     (message-cited-text ((t (:foreground "orange"))))
                     (message-header-contents ((t (:foreground "white"))))
                     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
                     (message-highlighted-header-contents ((t (:bold t :weight bold))))
                     (message-url ((t (:bold t :foreground "pink" :weight bold))))
                     (minibuffer-prompt ((t (:foreground "#ff3300" :weight bold))))
                     (mmm-face ((t (:background "black" :foreground "green"))))
                     (mode-line ((t (:background "black" :foreground "burlywood"))))
                     (mode-line-buffer-id ((t (:background "black" :foreground "burlywood"))))
                     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
                     (mode-line-inactive ((t (:background "grey10" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
                     (modeline-mousable ((t (:background "Gray80" :foreground "firebrick"))))
                     (modeline-mousable-minor-mode ((t (:background "Gray80" :foreground "green4"))))
                     (mouse ((t (:background "black"))))
                     (next-error ((t (:foreground "DarkBlue" :background "gray65"))))
                     (nobreak-space ((t (:foreground "cyan" :underline t))))
                     (org-level-1 ((((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue2" :weight extra-bold))))
                     (org-level-2 ((((class color) (min-colors 88) (background dark)) (:foreground "burlywood" :weight bold))))
                     (org-level-3 ((((class color) (min-colors 88) (background dark)) (:foreground "YellowGreen"))))
                     (org-level-4 ((((class color) (min-colors 88) (background dark)) (:foreground "green3"))))
                     (org-level-5 ((((class color) (min-colors 88) (background dark)) (:foreground "brown2"))))
                     (org-level-6 ((((class color) (min-colors 88) (background dark)) (:foreground "orange"))))
                     (org-level-7 ((((class color) (min-colors 88) (background dark)) (:foreground "red3"))))
                     (org-level-8 ((((class color) (min-colors 88) (background dark)) (:foreground "purple2"))))
                     (org-link ((((class color) (min-colors 88) (background dark)) (:foreground "cyan3"))))
                     (org-block ((t (:foreground "#8f82cf")))) ;;#8fb28f
                     (org-table ((t (:foreground "#9fc59f"))))
                     (org-meta-line ((t (:inherit font-lock-comment-face :weight normal))))
                     (org-column ((t (:background "black" :foreground "gray80" :strike-through
                                                  nil :underline nil :slant normal :weight
                                                  normal :height 98 :family "Courier New"))))
                     (org-done ((t (:foreground "ForestGreen" :strike-through t :weight normal))))
                     (org-todo ((t (:foreground "Red" :weight normal))))
                     (org-special-keyword ((t (:foreground "LightSalmon" :weight normal))))
                     (org-date ((t (:foreground "LightSalmon" :weight normal))))
					 (org-document-title ((t (:foreground "gray" :weight bold))))
					 (org-document-info ((t (:foreground "gray" :weight normal))))
                     (org-hide ((t (:foreground "grey20" :weight normal))))
					 (org-sexp-date ((t (:foreground "DodgerBlue3" :weight normal))))
                     (paren-blink-off ((t (:foreground "gray80"))))
                     (paren-match ((t (:background "MediumBlue"))))
                     (paren-mismatch ((t (:background "DeepPink" :foreground "LightSkyBlue"))))
                     (pointer ((t (nil))))
                     (primary-selection ((t (:background "gray65" :foreground "DarkBlue"))))
					 (preview-face ((((background dark)) (:background "#0F340A"))))
					 (preview-reference-face ((t (:background "black" :foreground "light blue" :weight bold :height 1.1))))
                     (query-replace ((t (:foreground "dark red" :background "paleturquoise"))))
                     (rainbow-delimiters-depth-1-face ((t (:foreground "gray60" :weight bold))))
                     (rainbow-delimiters-depth-2-face ((t (:foreground "#93a8c6" :weight bold))))
					 (rainbow-delimiters-depth-3-face ((t (:foreground "#b0b1a3" :weight bold))))
					 (rainbow-delimiters-depth-4-face ((t (:foreground "#97b098" :weight bold))))
					 (rainbow-delimiters-depth-5-face ((t (:foreground "#aebed8" :weight bold))))
					 (rainbow-delimiters-depth-6-face ((t (:foreground "#b0b0b3" :weight bold))))
					 (rainbow-delimiters-depth-7-face ((t (:foreground "#90a890" :weight bold))))
					 (rainbow-delimiters-depth-8-face ((t (:foreground "#a2b6da" :weight bold))))
					 (rainbow-delimiters-depth-9-face ((t (:foreground "#9cb6ad" :weight bold))))
                     (rainbow-delimiters-unmatched-face ((t (:foreground "dark red" :background "paleturquoise"))))
                     (red ((t (:foreground "red"))))
                     (region ((t (:foreground "gray90" :background "#0A248A"))))
                     (right-margin ((t (nil))))
                     (scroll-bar ((t (:foreground "systemscrollbar"))))
                     (secondary-selection ((t (:background "paleturquoise" :foreground "black"))))
                     (semantic-highlight-edits-face ((t (:background "gray20"))))
                     (semantic-unmatched-syntax-face ((t (:underline "red"))))
                     (senator-intangible-face ((t (:foreground "gray75"))))
                     (senator-momentary-highlight-face ((t (:background "gray30"))))
                     (senator-read-only-face ((t (:background "#664444"))))
                     (shadow ((t (:foreground "grey50"))))
                     (shell-option-face ((t (:foreground "LightSkyBlue1"))))
                     (shell-output-2-face ((t (:foreground "SeaGreen1"))))
                     (shell-output-3-face ((t (:foreground "Blue"))))
                     (shell-output-face ((t (:bold t :weight bold))))
                     (shell-prompt-face ((t (:foreground "red4"))))
                     (show-paren-match-face ((t (:bold t :foreground "grey85" 
                                        :background "blue"))))
                     (show-paren-mismatch ((t (:background "red" :foreground "white" :bold t))))
                     (speedbar-button-face ((t (:foreground "green3"))))
                     (speedbar-directory-face ((t (:foreground "light blue"))))
                     (speedbar-file-face ((t (:foreground "cyan"))))
                     (speedbar-highlight-face ((t (:background "sea green"))))
                     (speedbar-selected-face ((t (:foreground "red" :underline t))))
                     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
                     (speedbar-tag-face ((t (:foreground "yellow"))))
                     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :underline t :weight bold))))
                     (swbuff-default-face ((t (nil))))
                     (swbuff-separator-face ((t (:foreground "DodgerBlue1"))))
                     (tabbar-button ((t (:inherit tabbar-default :foreground "dark red"))))
                     (tabbar-button-highlight ((t (:inherit tabbar-default))))
                     (tabbar-default ((t (:inherit variable-pitch :background "gray80" :foreground "black"))))
                     (tabbar-highlight ((t (:underline t))))
                     (tabbar-selected ((t (:inherit tabbar-default :foreground "blue2" :weight bold))))
                     (tabbar-separator ((t (:inherit tabbar-default))))
                     (tabbar-unselected ((t (:inherit tabbar-default))))
                     (text-cursor ((t (:background "Red2" :foreground "black"))))
                     (tool-bar ((t (:background "gray80" :foreground "black"))))
                     (tooltip ((t (:family "helv" :background "systeminfowindow" :foreground "systeminfotext"))))
                     (underline ((t (:underline t))))
                     (variable-pitch ((t (:family "helv"))))
                     (vertical-border ((t (nil))))
                     (vertical-divider ((t (nil))))
                     (vm-xface ((t (:background "white" :foreground "black"))))
                     (vmpc-pre-sig-face ((t (:foreground "forestgreen"))))
                     (vmpc-sig-face ((t (:foreground "steelblue"))))
                     (which-func ((t (:foreground "DeepSkyBlue1"))))
                     (widget ((t (nil))))
                     (widget-button ((t (:bold t :weight bold))))
                     (widget-button-pressed ((t (:foreground "red"))))
                     (widget-documentation ((t (:foreground "lime green"))))
                     (widget-field ((t (:background "gray30" :foreground "gray85"))))
                     (widget-inactive ((t (:foreground "dim gray"))))
                     (widget-single-line-field ((t (:background "dim gray"))))
                     (x-face ((t (:background "white" :foreground "black"))))
                     (xrdb-option-name-face ((t (:foreground "red"))))
                     (yellow ((t (:foreground "yellow"))))
                     (zmacs-region ((t (:background "gray65"))))))))

(defun cl-dawn ()
  "Color theme Dawn, giving the warm yellowish background and various foreground colors."
  (interactive)
  (ignore-errors  (color-theme-install
                   '(color-theme-da-matlab
                     ((background-color . "#F5F5C3")
                     (background-mode . light)
                     (border-color . "black")
                     (foreground-color . "black")
                     (mouse-color . "black"))
					 (default ((t (:stipple nil :background "light goldenrod yellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :foundry "outline" :family "Bitstream Vera Sans Mono"))))
                     (bm-persistent-face ((t (:foreground "white" :background "darkblue" :weight bold))))
                     (bm-fringe-persistent-face ((t (:foreground "white" :background "darkblue" :weight bold))))
                     (bold ((t (:bold t :weight bold))))
                     (bold-italic ((t (:bold t :italic t :slant italic :weight bold))))
                     (border ((t (:background "yellow"))))
                     (buffer-menu-buffer ((t (:bold t :weight bold))))
                     (button ((t (:underline t))))
                     (comint-highlight-prompt ((t (:bold t :weight bold))))
                     (compilation-column-number ((t (:foreground "DarkBlue"))))
                     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
                     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
                     (compilation-line-number ((t (:bold t :weight ultra-bold :foreground "saddle brown"))))
                     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
                     (completions-common-part ((t (:width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "light goldenrod yellow" :stipple nil))))
                     (completions-first-difference ((t (:bold t :weight bold))))
                     (cursor ((t (:background "red3"))))
                     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
                     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
                     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
                     (custom-button-pressed-unraised ((t (:underline t :foreground "magenta4"))))
                     (custom-button-unraised ((t (:underline t))))
                     (custom-changed ((t (:background "blue1" :foreground "white"))))
                     (custom-comment ((t (:background "gray85"))))
                     (custom-comment-tag ((t (:foreground "blue4"))))
                     (custom-documentation ((t (nil))))
                     (custom-face-tag ((t (:bold t :family "helv" :weight bold :height 1.2))))
                     (custom-group-tag ((t (:bold t :foreground "blue1" :weight bold :height 1.2))))
                     (custom-group-tag-1 ((t (:bold t :family "helv" :foreground "red1" :weight bold :height 1.2))))
                     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
                     (custom-link ((t (:underline t :foreground "blue1"))))
                     (custom-modified ((t (:background "blue1" :foreground "white"))))
                     (custom-rogue ((t (:background "black" :foreground "pink"))))
                     (custom-saved ((t (:underline t))))
                     (custom-set ((t (:background "white" :foreground "blue1"))))
                     (custom-state ((t (:foreground "dark green"))))
                     (custom-themed ((t (:background "blue1" :foreground "white"))))
                     (custom-variable-button ((t (:bold t :underline t :weight bold))))
                     (custom-variable-tag ((t (:bold t :family "helv" :foreground "blue1" :weight bold :height 1.2))))

                     (diredp-file-name ((t (:foreground "gray30" :weight bold))))
                     (diredp-file-suffix ((t (:foreground "gray30" :weight normal))))
                     (diredp-dir-heading ((t (:foreground "DarkGreen" :weight bold ))))
                     (diredp-dir-priv ((t (:foreground "DarkBlue" :weight bold))))
                     (diredp-no-priv ((t )))
                     (diredp-exec-priv ((t (:foreground "Blue3" :weight bold))))
                     (diredp-read-priv ((t (:foreground "Green3" :weight bold))))
                     (diredp-write-priv ((t (:foreground "Red3" :weight bold))))
                     (diredp-link-priv ((t (:foreground "gray30" :underline t))))
                     (diredp-other-priv ((t (:foreground "gray10"))))
                     (diredp-rare-priv ((t (:foreground "red"))))
                     (diredp-flag-mark-line ((t (:background "DarkOrange4"))))
					 (diredp-date-time ((t (:foreground "black"))))

                     (ecb-analyse-bucket-element-face ((t (:foreground "brown" :height 1.0))))
                     (ecb-analyse-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
                     (ecb-analyse-face ((t (:background "cornflower blue" :foreground "yellow"))))
                     (ecb-analyse-general-face ((t (:height 1.0))))
                     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
                     (ecb-default-general-face ((t (:height 1.0))))
                     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
                     (ecb-directories-general-face ((t (:height 1.0))))
                     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
                     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
                     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
                     (ecb-history-general-face ((t (:height 1.0))))
                     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
                     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
                     (ecb-methods-general-face ((t (:height 1.0))))
                     (ecb-mode-line-data-face ((t (nil))))
                     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
                     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
                     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
                     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue" :height 1.0))))
                     (ecb-source-read-only-face ((t (:italic t :slant italic))))
                     (ecb-sources-general-face ((t (:height 1.0))))
                     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
                     (ecb-tree-guide-line-face ((t (:foreground "grey" :height 1.0))))
                     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
                     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
                     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
                     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
                     (escape-glyph ((t (:foreground "brown"))))
                     (file-name-shadow ((t (:foreground "grey50"))))
                     (fixed-pitch ((t (:family "courier"))))
                     (fl-comment-face ((t (:foreground "medium purple"))))
                     (fl-function-name-face ((t (:foreground "green"))))
                     (fl-keyword-face ((t (:foreground "LightGreen"))))
                     (fl-string-face ((t (:foreground "light coral"))))
                     (fl-type-face ((t (:foreground "cyan"))))
                     (flyspell-duplicate ((t (:foreground "Red3" :underline t :weight bold))))
                     (flyspell-incorrect ((t (:foreground "Red3" :underline t :weight bold))))
                     (font-lock-builtin-face ((t (:foreground "dark blue" :weight bold))))
                     (font-lock-comment-delimiter-face ((t (:foreground "dark green" :weight bold))))
                     (font-lock-comment-face ((t (:foreground "dark green" :weight bold))))
                     (font-lock-constant-face ((t (:bold t :foreground "DarkBlue" :weight extra-bold))))
                     (font-lock-doc-face ((t (:bold t :foreground "purple4" :weight bold))))
                     (font-lock-function-name-face ((t (:bold t :foreground "red4" :weight bold))))
                     (font-lock-keyword-face ((t (:bold t :foreground "blue3" :weight bold))))
                     (font-lock-negation-char-face ((t (nil))))
                     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue" :weight bold))))
                     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "NavyBlue" ))))
                     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "NavyBlue" ))))
                     (font-lock-string-face ((t (:bold t :foreground "DarkRed" :weight bold))))
                     (font-lock-type-face ((t (:foreground "dark blue" :weight bold))))
                     (font-lock-variable-name-face ((t (:bold t :foreground "saddle brown" :weight bold))))
                     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight extra-bold))))
                     (font-latex-math-face ((t (:foreground "red4"))))
                     (font-latex-sedate-face ((t (:foreground "blue"))))
                     (font-latex-sectioning-5-face ((t (:weight bold :bold t :foreground "red3"))))
                     (font-latex-bold-face ((t (:weight bold :bold t :foreground "dark green"))))
                     (font-latex-string-face ((t (:weight bold :bold nil :foreground "darkgreen"))))
                     (font-latex-warning-face ((t (:weight bold :bold nil :foreground "dark red"))))
                     (fringe ((t (:background "#E0F2D9" :foreground "#112233"))))
                     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
                     (help-argument-name ((t (nil))))
                     (highlight ((t (:background "#0A247A" :foreground "light goldenrod yellow"))))
                     (hl-line ((t (:background "#B5BA99"))))
                     (html-helper-bold-face ((t (:bold t :weight bold))))
                     (html-helper-italic-face ((t (:bold t :background "black" :foreground "yellow" :weight bold))))
                     (html-helper-underline-face ((t (:underline t))))
                     (ibuffer-deletion-face ((t (:foreground "red"))))
                     (ibuffer-marked-face ((t (:foreground "darkblue"))))
                     (ido-first-match ((t (:foreground "blue2" :bold t :weight ultra-bold))))
                     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
                     (ido-only-match ((t (:foreground "darkgreen" :weight ultra-bold))))
                     (ido-subdir ((t (:foreground "red"))))
                     (info-node ((t (:bold t :foreground "green3" :weight bold))))
                     (info-xref ((t (:bold t :weight bold :underline t))))
                     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
                     (isearch-secondary ((t (:foreground "red3"))))
                     (isearch-fail ((t (:background "red" :foreground "black"))))
                     (italic ((t (:italic t :slant italic))))
                     (lazy-highlight ((t (:background "paleturquoise"))))
                     (link ((t (:foreground "blue1" :underline t))))
                     (link-visited ((t (:underline t :foreground "magenta4"))))
                     (linum ((t (:inherit shadow :foreground "DarkGreen" :height 100 :weight normal))))
                     (match ((t (:background "yellow"))))
                     (man-bold ((t (:bold t :weight bold))))
                     (man-heading ((t (:bold t :weight bold))))
                     (man-italic ((t (:italic t :foreground "MediumBlue"))))
                     (man-xref ((t (:underline t))))
                     (matlab-unterminated-string-face  ((t (:foreground "red" :underline t :weight bold))))
                     (message-cited-text-face ((t (:foreground "red"))))
                     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold))))
                     (message-header-name-face ((t (:foreground "DarkGreen"))))
                     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
                     (message-header-other-face ((t (:foreground "#b00000"))))
                     (message-header-subject-face ((t (:foreground "green3"))))
                     (message-header-to-face ((t (:bold t :foreground "green2" :weight bold))))
                     (message-header-xheader-face ((t (:foreground "blue"))))
                     (message-mml-face ((t (:foreground "ForestGreen"))))
                     (message-separator-face ((t (:foreground "blue3"))))
                     (minibuffer-prompt ((t (:foreground "medium blue" :weight bold))))
                     (mode-line ((t (:background "#959A79" :foreground "black" :weight bold))))
                     (mode-line-buffer-id ((t (:background "wheat" :foreground "black" :weight bold))))
                     (mode-line-highlight ((t (:box (:line-width 2 :color "grey30" :style released-button)))))
                     (mode-line-inactive ((t (:background "#D5AA79" :foreground "black" :box (:line-width -1 :color "grey50" :style nil) :weight light))))
                     (modeline-mousable ((t (:background "wheat" :foreground "black"))))
                     (modeline-mousable-minor-mode ((t (:background "wheat" :foreground "black"))))
                     (mouse ((t (:background "black"))))
                     (next-error ((t (:background "gray80"))))
                     (nobreak-space ((t (:foreground "brown" :underline t))))
                     (org-level-1 ((((class color) (min-colors 88) (background dark)) (:foreground "brown" :weight extra-bold))))
                     (org-level-2 ((((class color) (min-colors 88) (background dark)) (:foreground "darkBlue" :weight bold))))
                     (org-level-3 ((((class color) (min-colors 88) (background dark)) (:foreground "DarkGreen3" :weight bold))))
                     (org-level-4 ((((class color) (min-colors 88) (background dark)) (:foreground "Black"))))
                     (org-level-5 ((((class color) (min-colors 88) (background dark)) (:foreground "Blue3"))))
                     (org-level-6 ((((class color) (min-colors 88) (background dark)) (:foreground "Brick3"))))
                     (org-level-7 ((((class color) (min-colors 88) (background dark)) (:foreground "DarkRed1"))))
                     (org-level-8 ((((class color) (min-colors 88) (background dark)) (:foreground "DarkBlue3"))))
                     (org-link ((((class color) (min-colors 88) (background dark)) (:foreground "blue3" :weight bold :underline t))))
                     (org-block ((t (:foreground "#1f128f")))) ;;#8fb28f
                     (org-table ((t (:foreground "black"))))
                     (org-meta-line ((t (:inherit font-lock-comment-face :weight normal))))
                     (org-special-keyword ((t (:foreground "LightSalmon3" :weight normal))))
                     (org-date ((t (:foreground "LightSalmon3" :weight normal))))
					 (org-sexp-date ((t (:foreground "DodgerBlue3" :weight normal))))
                     (org-hide ((t (:foreground "light goldenrod yellow3" :weight normal))))
					 (org-document-title ((t (:foreground "gray20" :weight bold))))
					 (org-document-info ((t (:foreground "gray20" :weight bold))))
                     (paren-blink-off ((t (:foreground "gray50"))))
                     (paren-match ((t (:background "MediumBlue"))))
                     (paren-mismatch ((t (:background "DeepPink" :foreground "LightSkyBlue"))))
                     (pointer ((t (nil))))
                     (primary-selection ((t (:background "DarkBlue" :foreground "Gray80"))))
                     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
                     (region ((t (:foreground "black" :background "gray80"))))
                     (scroll-bar ((t (:foreground "systemscrollbar"))))
                     (secondary-selection ((t (:background "darkslateblue" :foreground "black"))))
                     (semantic-decoration-on-private-members-face ((t (:background "#8fffff"))))
                     (semantic-decoration-on-protected-members-face ((t (:background "#fffff8"))))
                     (semantic-highlight-edits-face ((t (:background "gray90"))))
                     (semantic-tag-boundary-face ((t (:overline "blue"))))
                     (semantic-tag-highlight-face ((t (:background "#FFFFAA"))))
                     (semantic-tag-highlight-start-face ((t (:background "#FFFFAA"))))
                     (semantic-unmatched-syntax-face ((t (:underline "red"))))
                     (senator-intangible-face ((t (:foreground "gray25"))))
                     (senator-momentary-highlight-face ((t (:background "gray70"))))
                     (senator-read-only-face ((t (:background "#CCBBBB"))))
                     (shadow ((t (:foreground "grey50"))))
                     (show-paren-match ((t (:background "DodgerBlue"))))
                     (show-paren-mismatch ((t (:background "red" :foreground "white"))))
                     (speedbar-button-face ((t (:foreground "green4"))))
                     (speedbar-directory-face ((t (:foreground "blue4"))))
                     (speedbar-file-face ((t (:foreground "cyan4"))))
                     (speedbar-highlight-face ((t (:background "green"))))
                     (speedbar-selected-face ((t (:foreground "red" :underline t))))
                     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
                     (speedbar-tag-face ((t (:foreground "brown"))))
                     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :underline t :weight bold))))
                     (swbuff-default-face ((t (nil))))
                     (swbuff-separator-face ((t (:foreground "blue"))))
                     (tabbar-button-face ((t (:background "gray72" :family "helv" :foreground "dark red" :box (:line-width 2 :color "white" :style released-button) :height 0.8))))
                     (tabbar-default-face ((t (:family "helv" :background "gray72" :foreground "gray60" :height 0.8))))
                     (tabbar-selected-face ((t (:background "gray72" :family "helv" :foreground "blue" :box (:line-width 2 :color "white" :style released-button) :height 0.8))))
                     (tabbar-separator-face ((t (:foreground "gray60" :background "gray72" :family "helv" :height 0.16000000000000003))))
                     (tabbar-unselected-face ((t (:foreground "gray60" :background "gray72" :family "helv" :box (:line-width 2 :color "white" :style pressed-button) :height 0.8))))
                     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
                     (tooltip ((t (:family "helv" :background "systeminfowindow" :foreground "systeminfotext"))))
                     (underline ((t (:underline t))))
                     (variable-pitch ((t (:family "helv"))))
                     (vertical-border ((t (nil))))
                     (which-func ((t (:foreground "DeepSkyBlue4"))))
                     (widget-button ((t (:bold t :weight bold))))
                     (widget-button-pressed ((t (:foreground "red1"))))
                     (widget-documentation ((t (:foreground "dark green"))))
                     (widget-field ((t (:background "gray85"))))
                     (widget-inactive ((t (:foreground "grey50"))))
                     (widget-single-line-field ((t (:background "gray85"))))
                     (xref-keyword-face ((t (:foreground "blue"))))
                     (xref-list-default-face ((t (nil))))
                     (xref-list-pilot-face ((t (:foreground "navy"))))
                     (xref-list-symbol-face ((t (:foreground "navy"))))))))

(defun switch-dawn-night (&optional arg)
  "Changes color theme to the dark background theme (night).
With a prefix arg, changes to the warm bright background theme (dawn)."
  (interactive "P")
  (ignore-errors
    (if arg
        (cl-dawn)
      (cl-night))))
(provide 'color-theme-dawn-night)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; color-theme-dawn-night.el ends here
